from .equipo_serializer import EquipoSerializer
from .institucion_serializer import InstitucionSerializer
from .partido_serializer import PartidoSerializer
from .torneo_serializer import TorneoSerializer
from .temporada_serializer import TemporadaSerializer