# Generated by Django 5.2.7 on 2025-11-04 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('idinstitucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreinstitucion', models.CharField(max_length=250)),
                ('institucionactiva', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'institucion',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('idtemporada', models.AutoField(primary_key=True, serialize=False)),
                ('nombretemporada', models.CharField(max_length=250, unique=True)),
                ('descripciontemporada', models.CharField(max_length=250)),
                ('tipotemporada', models.CharField(choices=[('Amistosa', 'Amistosa'), ('Oficial', 'Oficial')], max_length=250)),
                ('fechainiciotemporada', models.DateTimeField()),
                ('fechafintemporada', models.DateTimeField()),
                ('temporadaactiva', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'temporada',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idequipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreequipo', models.CharField(max_length=250)),
                ('imagenequipo', models.BinaryField(blank=True, null=True)),
                ('equipoactivo', models.BooleanField(default=True)),
                ('idinstitucion', models.ForeignKey(db_column='id_institucion', on_delete=django.db.models.deletion.CASCADE, to='torneo.institucion')),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('idtorneo', models.AutoField(primary_key=True, serialize=False)),
                ('nombretorneo', models.CharField(max_length=250, unique=True)),
                ('descripciontorneo', models.CharField(max_length=250)),
                ('fechainiciotorneo', models.DateTimeField()),
                ('fechafintorneo', models.DateTimeField()),
                ('torneoactivo', models.BooleanField(default=False)),
                ('idtemporada', models.ForeignKey(db_column='id_temporada', on_delete=django.db.models.deletion.CASCADE, to='torneo.temporada')),
            ],
            options={
                'db_table': 'torneo',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('idpartido', models.AutoField(primary_key=True, serialize=False)),
                ('fechapartido', models.DateTimeField()),
                ('marcadorequipolocal', models.IntegerField(blank=True, null=True)),
                ('marcadorequipovisitante', models.IntegerField(blank=True, null=True)),
                ('idequipolocal', models.ForeignKey(db_column='id_equipo_local', on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='torneo.equipo')),
                ('idequipovisitante', models.ForeignKey(db_column='id_equipo_visitante', on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='torneo.equipo')),
                ('idtemporada', models.ForeignKey(db_column='id_temporada', on_delete=django.db.models.deletion.CASCADE, to='torneo.temporada')),
                ('idtorneo', models.ForeignKey(db_column='id_torneo', on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
            options={
                'db_table': 'partido',
            },
        ),
    ]
