# Generated by Django 5.2.7 on 2025-10-19 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idequipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreequipo', models.CharField(max_length=100, unique=True)),
                ('logoequipo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('idtorneo', models.AutoField(primary_key=True, serialize=False)),
                ('nombretorneo', models.CharField(max_length=100, unique=True)),
                ('descripciontorneo', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('idpartido', models.AutoField(primary_key=True, serialize=False)),
                ('marcadorequipolocal', models.IntegerField(blank=True, null=True)),
                ('marcadorequipovisitante', models.IntegerField(blank=True, null=True)),
                ('fechapartido', models.DateTimeField(unique=True)),
                ('tipopartido', models.BooleanField()),
                ('idequipolocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='torneo.equipo')),
                ('idequipovisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='torneo.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('idtemporada', models.AutoField(primary_key=True, serialize=False)),
                ('nombretemporada', models.CharField(max_length=100)),
                ('tipotemporada', models.BooleanField()),
                ('idtorneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='TorneoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.partido')),
                ('idtorneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
            options={
                'unique_together': {('idtorneo', 'idpartido')},
            },
        ),
    ]
