# Generated by Django 5.2.7 on 2025-11-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='partidosubido',
            field=models.BooleanField(default=False),
        ),
    ]
