# Generated by Django 5.2.7 on 2025-11-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagenequipo',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/'),
        ),
    ]
